Terraform Remote Backend Check

diff --git a/.github/workflows/terraform-remote-backend-check.yml b/.github/workflows/terraform-remote-backend-check.yml
--- a/.github/workflows/terraform-remote-backend-check.yml
+++ b/.github/workflows/terraform-remote-backend-check.yml
@@ -1,69 +1,98 @@
-name: Terraform Backend Check
+name: Terraform Remote Backend Check
 
 on:
+  workflow_call:
+    inputs:
+      branch:
+        required: true
+        type: string
+
   workflow_dispatch:
+    inputs:
+      branch:
+        description: "Branch To Run Workflow - Leave Empty For Current Branch"
+        required: false
+        type: string
+
+  pull_request:
+    branches:
+      - dev
+      - staging
+      - main
+    paths:
+      - modules/**
+      - environments/dev/**
+      - environments/staging/**
+      - environments/production/**
+      - environments/terraform-backend/**
+      - main.tf
+      - variables.tf
 
 jobs:
-  backend-check:
+  Remote-Backend-Check:
     runs-on: ubuntu-latest
+    env:
+      TF_LOG: "ERROR"
+      INPUT_BRANCH: ${{ inputs.branch }}
+      DISPATCH_BRANCH: ${{ github.event.inputs.branch }}
+
     outputs:
-      env_name: ${{ steps.set-env.outputs.env }}
-      tfvars_file: ${{ steps.set-env.outputs.tfvars_file }}
-      backend_exists: ${{ steps.set-backend.outputs.backend_exists }}
+      env_name: ${{ steps.detect-env.outputs.env }}
 
     steps:
       - name: Checkout Repo
         uses: actions/checkout@v4
 
-      # Determine Environment & Backend TFVARS File Based On Branch - Workflow Dispatch
-      - name: Determine Branch Environment
-        id: set-env
+      # Determine Branch & Environment
+      - name: Determine Branch & Enviroment
+        id: detect-env
+        shell: bash
         run: |
-          if [ "${{ github.event_name }}" == "pull_request" ]; then
-                BRANCH="${{ github.base_ref }}"
-              else
-                BRANCH="${{ github.ref_name }}"
-              fi
+          echo "Event: $GITHUB_EVENT_NAME"
+
+           if [ "$GITHUB_EVENT_NAME" = "workflow_call" ]; then
+            BRANCH="$INPUT_BRANCH"
+
+           elif [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ] && [ -n "$DISPATCH_BRANCH" ]; then
+            BRANCH="$DISPATCH_BRANCH"
+
+          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
+            BRANCH="$GITHUB_BASE_REF"
+
+          else
+            BRANCH="${GITHUB_REF#refs/heads/}"
+          fi
+
+          echo "Branch: $BRANCH"
 
           case "$BRANCH" in
             dev) ENV="dev" ;;
             staging) ENV="staging" ;;
             main) ENV="production" ;;
             *) echo "Invalid Branch: $BRANCH"; exit 1 ;;
-          esac
+            esac
 
           TFVARS_FILE="environments/${ENV}/backend.tfvars"
 
           echo "ENV=$ENV" >> $GITHUB_ENV
           echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
-
           echo "env=$ENV" >> $GITHUB_OUTPUT
-          echo "tfvars_file=$TFVARS_FILE" >> $GITHUB_OUTPUT
 
           echo "Environment: $ENV"
           echo "Using TFVARS File: $TFVARS_FILE"
 
-      # Clear Cahce
-      - name: Clear Cache
+        # Terraform Backend Folders & Files
+      - name: Terraform Backend Folders & Files
         run: |
-          echo "Cleaning Cache..."
-          rm -rf .terraform .terraform.lock.hcl
+          echo "Terraform Backend Folders & Files:"
+          for dir in environments/terraform-backend/*; do
+            if [ -d "$dir" ]; then
+              echo "Folder: $dir"
+              ls -1 "$dir"
+            fi
+          done
 
-          rm -rf environments/${ENV}/.terraform
-          rm -f environments/${ENV}/.terraform.lock.hcl
-
-          echo "Cleanup Complete"
-
-        # Azure Authentication
-      - name: Azure Login
-        run: |
-          az login --service-principal \
-            -u ${{ secrets.AZURE_CLIENT_ID }} \
-            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
-            --tenant ${{ secrets.AZURE_TENANT_ID }}
-          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
-
-        # Determine Variables
+      # Determine Backend Variables
       - name: Determine Backend Variables
         run: |
           BACKEND_FILE="${TFVARS_FILE}"
@@ -88,6 +117,16 @@ jobs:
            echo "STORAGE_CONTAINER_NAME=$CONTAINER" >> $GITHUB_ENV
            echo "STATE_KEY_BACKEND=$KEY" >> $GITHUB_ENV
 
+        # Azure Authentication
+      - name: Azure Login
+        run: |
+          az login --service-principal \
+            -u ${{ secrets.AZURE_CLIENT_ID }} \
+            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
+            --tenant ${{ secrets.AZURE_TENANT_ID }}
+          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
+
+        # Check Azure Remote Backend
       - name: Confirming Backend..
         id: set-backend
         shell: bash
@@ -106,7 +145,7 @@ jobs:
            --name "$RG_NAME" \
            --output none; then
               echo "Resource Group '$RG_NAME' Missing"
-              backend_exists=false
+              exit 1
               echo "Skipping Further Checks.."
           else
             echo "Resource Group Exists"
@@ -118,7 +157,9 @@ jobs:
               --resource-group "$RG_NAME" \
               --output none; then
                 echo "Storage Account Missing"
-                backend_exists=false
+                exit 1
+            else
+              echo "Storage Account Exists"
             fi
 
             # Container
@@ -129,7 +170,9 @@ jobs:
               --auth-mode login \
               --output none; then
                 echo "Container Missing"
-                backend_exists=false
+                exit 1
+              else
+                echo "Container Exists"
             fi  
 
             # State Key
@@ -144,61 +187,13 @@ jobs:
               --output tsv 2>/dev/null)
 
             if [[ "$BLOB_EXISTS" != "true" ]]; then
-              echo "Backend Missing"
-              backend_exists=false
+              echo "State Key Missing"
+              exit 1
             else
               echo "Backend Exists"
             fi
-            echo "Backend Exists: $backend_exists"
-          fi
 
-           # Set Output For Triggers
-          echo "backend_exists=$backend_exists" >> $GITHUB_OUTPUT
-          echo "backend_exists=$backend_exists" >> $GITHUB_ENV
-          echo "Backend Exists: $backend_exists"
-
-  trigger-infra-deployment:
-    name: Trigger Infrastructure Deployment
-    runs-on: ubuntu-latest
-    needs: backend-check
-    if: needs.backend-check.outputs.backend_exists == 'true'
-
-    env:
-      ENV: ${{ needs.backend-check.outputs.env_name }}
-      TFVARS_FILE: ${{ needs.backend-check.outputs.tfvars_file }}
-
-    steps:
-      - name: Deployment Workflow Trigger
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.PAT_TOKEN }}
-          script: |
-            await github.rest.actions.createWorkflowDispatch({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              workflow_id: "terraform-infrastructure-deployment.yml",
-              ref: context.ref,
-            });
-
-  trigger-backend-bootstrap:
-    name: Trigger Backend Bootstrap
-    runs-on: ubuntu-latest
-    needs: backend-check
-    if: needs.backend-check.outputs.backend_exists == 'false'
-
-    env:
-      ENV: ${{ needs.backend-check.outputs.env_name }}
-      TFVARS_FILE: ${{ needs.backend-check.outputs.tfvars_file }}
-
-    steps:
-      - name: Trigger Bootstrap Workflow
-        uses: actions/github-script@v6
-        with:
-          github-token: ${{ secrets.PAT_TOKEN }}
-          script: |
-            await github.rest.actions.createWorkflowDispatch({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              workflow_id: "terraform-backend-bootstrap.yml",
-              ref: context.ref,
-            });
+           # Backend Exists If Reached This Step
+           echo "backend_exists=true" >> $GITHUB_OUTPUT
+           echo "backend_exists=true" >> $GITHUB_ENV
+           echo "Backend Exists: true"
