- Terraform Static Analysis: Env Output Adjustments, Detect Env Syntax, TF Var File, Changed Dependency

diff --git a/.github/workflows/terraform-static-analysis.yml b/.github/workflows/terraform-static-analysis.yml
--- a/.github/workflows/terraform-static-analysis.yml
+++ b/.github/workflows/terraform-static-analysis.yml
@@ -15,7 +15,9 @@ jobs:
     runs-on: ubuntu-latest
     env:
       TF_LOG: "ERROR"
-    outputs: ${{ steps.detect-env.outputs.env }}
+
+    outputs:
+      env_name: ${{ steps.detect-env.outputs.env }}
 
     steps:
       - name: Checkout Repo
@@ -26,23 +28,23 @@ jobs:
         id: detect-env
         run: |
           if [ "${{ github.event_name }}" == "pull_request" ]; then
-                BRANCH="${{ github.base_ref }}"
-              else
-                BRANCH="${{ github.ref_name }}"
-              fi
+            BRANCH="${{ github.base_ref }}"
+          else
+            BRANCH="${{ github.ref_name }}"
+          fi
 
-           case "$BRANCH" in
-              dev) ENV="dev" ;;
-              staging) ENV="staging" ;;
-              main) ENV="production" ;;
-              *) echo "Invalid branch: $BRANCH"; exit 1 ;;
+          case "$BRANCH" in
+            dev) ENV="dev" ;;
+            staging) ENV="staging" ;;
+            main) ENV="production" ;;
+            *) echo "Invalid branch: $BRANCH"; exit 1 ;;
             esac
 
-            TFVARS_FILE="environments/${ENV}/${ENV}.tfvars"
+          TFVARS_FILE="environments/${ENV}/${ENV}.tfvars"
 
-            echo "ENV=$ENV" >> $GITHUB_ENV
-            echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
-            echo "env=$ENV" >> $GITHUB_OUTPUT
+          echo "ENV=$ENV" >> $GITHUB_ENV
+          echo "TFVARS_FILE=$TFVARS_FILE" >> $GITHUB_ENV
+          echo "env=$ENV" >> $GITHUB_OUTPUT
 
           echo "Environment: $ENV"
           echo "Using TFVARS File: $TFVARS_FILE"
@@ -81,7 +83,7 @@ jobs:
         # Initialize Terraform Without Backend
       - name: Initialize Terraform
         working-directory: .
-        run: terraform init -backend=false -var-file=${ENV}.tfvars
+        run: terraform init -backend=false -var-file="$TFVARS_FILE"
 
         # Validation
       - name: Terraform Validate
@@ -95,7 +97,7 @@ jobs:
     needs: terraform-format-validate
     env:
       ENV: ${{ needs.terraform-format-validate.outputs.env_name }}
-      TFVARS_FILE: ${{ 'environments/' + needs.terraform-format-validate.outputs.env_name + '/' + needs.terraform-format-validate.outputs.env_name + '.tfvars' }}
+      TFVARS_FILE: environments/${{ needs.terraform-format-validate.outputs.env_name }}/${{ needs.terraform-format-validate.outputs.env_name }}.tfvars
 
     steps:
       - name: Checkout Repo
@@ -123,7 +125,7 @@ jobs:
         # Initialize Terraform Without Backend
       - name: Terraform Init
         working-directory: .
-        run: terraform init -backend=false -var-file=${ENV}.tfvars
+        run: terraform init -backend=false -var-file="$TFVARS_FILE"
 
         # Setup TFLint
       - name: Setup TFLint
@@ -167,13 +169,16 @@ jobs:
     if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
     name: Checkov Security Analysis
     runs-on: ubuntu-latest
-    needs: tflint
+    needs:
+      - terraform-format-validate
+      - tflint
+
     env:
       ENV: ${{ needs.terraform-format-validate.outputs.env_name }}
-      TFVARS_FILE: ${{ 'environments/' + needs.terraform-format-validate.outputs.env_name + '/' + needs.terraform-format-validate.outputs.env_name + '.tfvars' }}
+      TFVARS_FILE: environments/${{ needs.terraform-format-validate.outputs.env_name }}/${{ needs.terraform-format-validate.outputs.env_name }}.tfvars
 
     outputs:
-      env_name: ${{ env.ENV }}
+      env_name: ${{ steps.set-env.outputs.env }}
 
     steps:
       - name: Checkout Repo
